/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class Service {

    private ToDoDAO dao;

    @Autowired
    public Service(ToDoDAO dao) {
        this.dao = dao;
    }
    
    @RequestMapping("/")
    public String index(Model model) {
        ToDo[] toDoList = dao.getList();
        model.addAttribute("toDoList", toDoList);
        model.addAttribute("size", toDoList.length);
    	return "index";
    }

    @RequestMapping(value = "/add", method = RequestMethod.GET)
    public @ResponseBody ToDo[] add(@RequestParam String description) {
        return dao.add(description);
    }

    @RequestMapping(value = "/getList", method = RequestMethod.GET)
    public @ResponseBody ToDo[] getList() {
        return dao.getList();
    }

    @RequestMapping(value = "/update", method = RequestMethod.GET)
    public @ResponseBody ToDo[] update(@RequestParam int id, @RequestParam String description) {
        return dao.update(id, description);
    }

    @RequestMapping(value = "/delete", method = RequestMethod.GET)
    public @ResponseBody ToDo[] delete(@RequestParam int id) {
        return dao.delete(id);
    }
}

